# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

pod 'AFNetworking', '~> 3.0'
pod 'Firebase', '>= 2.4.2'
target 'nflhackathon' do

end

target 'nflhackathonTests' do

end

target 'nflhackathonUITests' do

end

